version: '3.1'
services:
  db:
    image: mysql
    container_name: distprog-inventory-management
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - distprog-inventory-management:/var/lib/mysql

volumes:
  distprog-inventory-management:
