#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    url: jdbc:postgresql://localhost:5432/erp?createDatabaseIfNotExist=true
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
